paths:
  /api/category:
    get:
      summary: Get all categories
      tags:
        - Categories
      responses:
        200:
          description: List of all categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

    post:
      summary: Create a new category
      tags:
        - Categories
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryCreate'
      responses:
        201:
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'

  /api/categories/{id}:
    get:
      summary: Get a category by ID
      tags:
        - Categories
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Category details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'

    put:
      summary: Update a category
      tags:
        - Categories
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryUpdate'
      responses:
        200:
          description: Category updated successfully

    delete:
      summary: Delete a category
      tags:
        - Categories
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        204:
          description: Category deleted successfully

components:
  schemas:
    Category:
      type: object
      properties:
        name:
          type: string
          example: 'Electronics'
        parentCategory:
          type: string
          description: 'ID of the parent category'
          example: '5f8d04034b432b3a2e3b9f21'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CategoryCreate:
      type: object
      properties:
        name:
          type: string
          example: 'Electronics'
        parentCategory:
          type: string
          description: 'ID of the parent category'
          example: '5f8d04034b432b3a2e3b9f21'

    CategoryUpdate:
      type: object
      properties:
        name:
          type: string
          example: 'Updated Electronics'
        parentCategory:
          type: string
          description: 'ID of the new parent category'
          example: '5f8d04034b432b3a2e3b9f22'

securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
